### ISSUE TITLE
第4课查询数据章节返回数据有问题

### ISSUE THREAD

**Issue by 78986912** [peiss/ant-learn-pandas#2]
第4课查询数据章节，使用自定义函数，返回数据有问题，定义的空气质量==1，返回的结果有数值为3的

**Comment by peiss** [comment]
已修复，可以重新看下；

之前写的是：return df.index.str.startswith("2018-09") & df["aqiLevel"]==1

这里写错了，因为逻辑运算符&两边的判断条件，都需要加上小括号；
已经改成：

return df.index.str.startswith("2018-09") & (df["aqiLevel"]==1)
