### ISSUE TITLE
29： Pandas和Flask配合实现快速在网页上展示表格数据是不是没有写完

### ISSUE THREAD

**Issue by wangqlpython** [peiss/ant-learn-pandas#3]
兄弟，你写得真好，让我收获不少，请教下这页是不是没有写完，

**Comment by peiss** [comment]
https://github.com/peiss/ant-learn-pandas/tree/master/pandas-flask

哦，我看了下，没问题的。这个代码在这个目录

这个ipynb只是一个说明的作用

**Comment by wangqlpython** [comment]
谢谢！



---原始邮件---
发件人: "peiss"<notifications@github.com&gt;
发送时间: 2020年2月25日(周二) 下午2:04
收件人: "peiss/ant-learn-pandas"<ant-learn-pandas@noreply.github.com&gt;;
抄送: "wangqlpython"<258347307@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [peiss/ant-learn-pandas] 29： Pandas和Flask配合实现快速在网页上展示表格数据是不是没有写完 (#3)



https://github.com/peiss/ant-learn-pandas/tree/master/pandas-flask
 
哦，我看了下，没问题的。这个代码在这个目录
 
这个ipynb只是一个说明的作用
